"""initial schema

Revision ID: 035210435ff8
Revises: 
Create Date: 2026-07-02 12:20:28.406683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035210435ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparable_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('case_no', sa.String(length=64), nullable=True),
    sa.Column('onbid_no', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('property_type', sa.String(length=40), nullable=True),
    sa.Column('appraisal_price', sa.BigInteger(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('case_no', sa.String(length=64), nullable=True),
    sa.Column('item_no', sa.String(length=16), nullable=True),
    sa.Column('onbid_no', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('property_type', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=True),
    sa.Column('comparable_case_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=24), nullable=False),
    sa.Column('sale_price', sa.BigInteger(), nullable=True),
    sa.Column('sale_ratio', sa.Float(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['comparable_case_id'], ['comparable_cases.id'], ),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comp_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparable_case_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('match_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['comparable_case_id'], ['comparable_cases.id'], ),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('appraisal_price', sa.BigInteger(), nullable=True),
    sa.Column('min_price', sa.BigInteger(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id_or_url', sa.String(length=500), nullable=True),
    sa.Column('match_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_links')
    op.drop_table('daily_snapshots')
    op.drop_table('comp_links')
    op.drop_table('auction_results')
    op.drop_table('watchlist_items')
    op.drop_table('comparable_cases')
    # ### end Alembic commands ###
